### PR TITLE
UPPSF-549 Hide broken concepts

### PR DESCRIPTION
**Pull request by karsov**
Do not add broken concepts without canonical node to the export.
Rewrite to not use Identifier nodes in the queries.

### CODE REVIEW

**Comment by karsov** [comment]
> What was the fix exactly? I don't see what was the cause for the bug in the first place.
> 
> From what I understand from the query, with the removal of the Identifier nodes, in some cases we would return less information. For instance `coalesce(x.factsetId,factset.value) as factsetId` x.factsetId could be null. Is this a problem?

There were two problems before:
1. EQUIVALENT_TO relationship was an optional match, which meant that we can return a concept without a canonical node (and indeed we returned such)
2. Identifier nodes were used - this is a thing we want to deprecate and get that information from better places

**Comment by ivan-p-nikolov** [comment]
> EQUIVALENT_TO relationship was an optional match, which meant that we can return a concept without a canonical node (and indeed we returned such)

Is it possible to write a test for this situation? Sounds like it's possible.

> Identifier nodes were used - this is a thing we want to deprecate and get that information from better places

From what I understand from the query, there is information stored in the Identifier nodes, and by removing them from the query we remove this information as well. So my question is: Do we care for that information? And if we do. Do we have a plan for transitioning from the old (with Identifier nodes) way to the new (without) one.

**Comment by karsov** [comment]
> From what I understand from the query, there is information stored in the Identifier nodes, and by removing them from the query we remove this information as well. So my question is: Do we care for that information? And if we do. Do we have a plan for transitioning from the old (with Identifier nodes) way to the new (without) one.

That information was redundant. All the information is preserved in the new query.

**Comment by karsov** [comment]
> > EQUIVALENT_TO relationship was an optional match, which meant that we can return a concept without a canonical node (and indeed we returned such)
> 
> Is it possible to write a test for this situation? Sounds like it's possible.

On first thought it looks like a good idea to me too. However on second thought in order to make such test we need to write a broken concept (without a canonical node). But we are using `concepts-rw-neo4j` for writing test data and I personally don't know a good way to force it to write invalid data to Neo4j.

**Pull request merged**
